// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* hello.h
   Generated by wsdl2h 2.8.91 from hello.wsdl and typemap.dat
   2023-11-21 08:42:06 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on hello.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2019, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   /media/sf_share_win/code/gsoap/hello.wsdl                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	Hello_USCOREBinding 
//gsoap ns1  service type:	Hello_USCOREPortType 
//gsoap ns1  service port:	http://localhost/SayHello/ 
//gsoap ns1  service namespace:	urn:examples:helloservice 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage HelloService Definitions

@section HelloService_bindings Service Bindings

  - @ref Hello_USCOREBinding

@section HelloService_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page Hello_USCOREBinding Binding "Hello_USCOREBinding"

@section Hello_USCOREUSCOREBinding_service Service Documentation "Hello_USCOREBinding"
WSDL File for HelloService

@section Hello_USCOREBinding_operations Operations of Binding "Hello_USCOREBinding"

  - @ref ns1__sayHello

@section Hello_USCOREBinding_ports Default endpoints of Binding "Hello_USCOREBinding"

  - http://localhost/SayHello/

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   Hello_USCOREBinding                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns1__sayHello                                                            *
 *                                                                            *
\******************************************************************************/


/** Operation "ns1__sayHello" of service binding "Hello_USCOREBinding".

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Default endpoints:
    - http://localhost/SayHello/

  - Default SOAP action or REST location path:
    - "sayHello"

  - Addressing input action: "sayHello"

  - Addressing output action: "sayHelloResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__sayHello(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    char*                               firstName,
    // output parameters:
    char*                              *greeting
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__sayHello(
    struct soap *soap,
    // input parameters:
    char*                               firstName,
    // output parameters:
    char*                              *greeting
  );
@endcode

*/

/* remote_cmd  */
//gsoap ns1  service method-protocol:	sayHello SOAP
//gsoap ns1  service method-style:	sayHello rpc
//gsoap ns1  service method-encoding:	sayHello http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-input-action:	sayHello sayHello
//gsoap ns1  service method-output-action:	sayHello sayHelloResponse
int ns1__sayHello(
    char*                               :firstName,	///< Input parameter, :unqualified name as per RPC encoding
    char*                              *:greeting	///< Output parameter, :unqualified name as per RPC encoding
);

/*************************** audio dev interface *********************************************/
//gsoap ns service method: sayHello set audio sample
int ns1__audio_sample_set(int sample, int *ret);

//gsoap ns service method: sayHello get audio sample
int ns1__audio_sample_get(int *sample);

//gsoap ns service method: sayHello get button status
int ns1__audio_button_status_get(int *status);


/*************************** video dev interface *********************************************/

//gsoap ns service method: sayHello get fps
int ns1__video_fps_get(int *fps);
//gsoap ns service method: sayHello set fps
int ns1__video_fps_set(int fps, int *ret);

//gsoap ns service method: sayHello get width & height	
int ns1__video_wh_get(int *w, int *h);
//gsoap ns service method: sayHello set width & height
int ns1__video_wh_set(int w, int h, int *ret);
	
//gsoap ns service method: sayHello set bitrate
int ns1__video_bitrate_get(int *bitrate_max, int *bitrate_min);
//gsoap ns service method: sayHello set bitrate
int ns1__video_bitrate_set(int bitrate_max, int bitrate_min, int *ret);

//gsoap ns service method: sayHello get i frame interval
int ns1__video_interval_get(int *i_interval);
//gsoap ns service method: sayHello set i frame interval
int ns1__video_interval_set(int i_interval, int *ret);

//gsoap ns service method: sayHello report  log info
int ns1__log_info(const char *info, void);

//gsoap ns service method: notify status
int ns1__status_notify(const char *info, void);

//gsoap ns service method: video cfg set
int ns1__video_cfg_set(char*  cfg_data, int len, int *ret);

//gsoap ns service method: video cfg get
int ns1__video_cfg_get(char **cfg_data);

//gsoap ns service method: audio cfg set
int ns1__audio_cfg_set(char*  cfg_data, int len, int *ret);

//gsoap ns service method: audio cfg get
int ns1__audio_cfg_get(char **cfg_data);

//gsoap ns service method: audio cfg set
int ns1__osd_text_set(char*  text_data, int len, int *ret);

int ns1__hdmi_wh_set(int w, int h, int fps, int *ret);

/** @page Hello_USCOREBinding Binding "Hello_USCOREBinding"

@section Hello_USCOREBinding_policy_enablers Policy Enablers of Binding "Hello_USCOREBinding"

None specified.

*/

/* End of hello.h */
