/* soapClient.c
   Generated by gSOAP 2.8.114 for hello.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.114 2024-04-02 08:24:42 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sayHello(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *firstName, char **greeting)
{	if (soap_send_ns1__sayHello(soap, soap_endpoint, soap_action, firstName) || soap_recv_ns1__sayHello(soap, greeting))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__sayHello(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *firstName)
{	struct ns1__sayHello soap_tmp_ns1__sayHello;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	if (soap_action == NULL)
		soap_action = "sayHello";
	soap_tmp_ns1__sayHello.firstName = firstName;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns1__sayHello(soap, &soap_tmp_ns1__sayHello);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__sayHello(soap, &soap_tmp_ns1__sayHello, "ns1:sayHello", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__sayHello(soap, &soap_tmp_ns1__sayHello, "ns1:sayHello", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__sayHello(struct soap *soap, char **greeting)
{
	struct ns1__sayHelloResponse *soap_tmp_ns1__sayHelloResponse;
	if (!greeting)
		return soap_closesock(soap);
	*greeting = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__sayHelloResponse = soap_get_ns1__sayHelloResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__sayHelloResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (greeting && soap_tmp_ns1__sayHelloResponse->greeting)
		*greeting = *soap_tmp_ns1__sayHelloResponse->greeting;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_sample_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int sample, int *ret)
{	if (soap_send_ns1__audio_sample_set(soap, soap_endpoint, soap_action, sample) || soap_recv_ns1__audio_sample_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_sample_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int sample)
{	struct ns1__audio_sample_set soap_tmp_ns1__audio_sample_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__audio_sample_set.sample = sample;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_sample_set(soap, &soap_tmp_ns1__audio_sample_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_sample_set(soap, &soap_tmp_ns1__audio_sample_set, "ns1:audio-sample-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_sample_set(soap, &soap_tmp_ns1__audio_sample_set, "ns1:audio-sample-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_sample_set(struct soap *soap, int *ret)
{
	struct ns1__audio_sample_setResponse *soap_tmp_ns1__audio_sample_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__audio_sample_setResponse = soap_get_ns1__audio_sample_setResponse(soap, NULL, "ns1:audio-sample-setResponse", NULL);
	if (!soap_tmp_ns1__audio_sample_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__audio_sample_setResponse->ret)
		*ret = *soap_tmp_ns1__audio_sample_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_sample_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *sample)
{	if (soap_send_ns1__audio_sample_get(soap, soap_endpoint, soap_action) || soap_recv_ns1__audio_sample_get(soap, sample))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_sample_get(struct soap *soap, const char *soap_endpoint, const char *soap_action)
{	struct ns1__audio_sample_get soap_tmp_ns1__audio_sample_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_sample_get(soap, &soap_tmp_ns1__audio_sample_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_sample_get(soap, &soap_tmp_ns1__audio_sample_get, "ns1:audio-sample-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_sample_get(soap, &soap_tmp_ns1__audio_sample_get, "ns1:audio-sample-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_sample_get(struct soap *soap, int *sample)
{
	struct ns1__audio_sample_getResponse *soap_tmp_ns1__audio_sample_getResponse;
	if (!sample)
		return soap_closesock(soap);
	soap_default_int(soap, sample);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__audio_sample_getResponse = soap_get_ns1__audio_sample_getResponse(soap, NULL, "ns1:audio-sample-getResponse", NULL);
	if (!soap_tmp_ns1__audio_sample_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (sample && soap_tmp_ns1__audio_sample_getResponse->sample)
		*sample = *soap_tmp_ns1__audio_sample_getResponse->sample;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_button_status_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *status)
{	if (soap_send_ns1__audio_button_status_get(soap, soap_endpoint, soap_action) || soap_recv_ns1__audio_button_status_get(soap, status))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_button_status_get(struct soap *soap, const char *soap_endpoint, const char *soap_action)
{	struct ns1__audio_button_status_get soap_tmp_ns1__audio_button_status_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_button_status_get(soap, &soap_tmp_ns1__audio_button_status_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_button_status_get(soap, &soap_tmp_ns1__audio_button_status_get, "ns1:audio-button-status-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_button_status_get(soap, &soap_tmp_ns1__audio_button_status_get, "ns1:audio-button-status-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_button_status_get(struct soap *soap, int *status)
{
	struct ns1__audio_button_status_getResponse *soap_tmp_ns1__audio_button_status_getResponse;
	if (!status)
		return soap_closesock(soap);
	soap_default_int(soap, status);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__audio_button_status_getResponse = soap_get_ns1__audio_button_status_getResponse(soap, NULL, "ns1:audio-button-status-getResponse", NULL);
	if (!soap_tmp_ns1__audio_button_status_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (status && soap_tmp_ns1__audio_button_status_getResponse->status)
		*status = *soap_tmp_ns1__audio_button_status_getResponse->status;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_fps_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *fps)
{	if (soap_send_ns1__video_fps_get(soap, soap_endpoint, soap_action) || soap_recv_ns1__video_fps_get(soap, fps))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_fps_get(struct soap *soap, const char *soap_endpoint, const char *soap_action)
{	struct ns1__video_fps_get soap_tmp_ns1__video_fps_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_fps_get(soap, &soap_tmp_ns1__video_fps_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_fps_get(soap, &soap_tmp_ns1__video_fps_get, "ns1:video-fps-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_fps_get(soap, &soap_tmp_ns1__video_fps_get, "ns1:video-fps-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_fps_get(struct soap *soap, int *fps)
{
	struct ns1__video_fps_getResponse *soap_tmp_ns1__video_fps_getResponse;
	if (!fps)
		return soap_closesock(soap);
	soap_default_int(soap, fps);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_fps_getResponse = soap_get_ns1__video_fps_getResponse(soap, NULL, "ns1:video-fps-getResponse", NULL);
	if (!soap_tmp_ns1__video_fps_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (fps && soap_tmp_ns1__video_fps_getResponse->fps)
		*fps = *soap_tmp_ns1__video_fps_getResponse->fps;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_fps_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int fps, int *ret)
{	if (soap_send_ns1__video_fps_set(soap, soap_endpoint, soap_action, fps) || soap_recv_ns1__video_fps_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_fps_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int fps)
{	struct ns1__video_fps_set soap_tmp_ns1__video_fps_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__video_fps_set.fps = fps;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_fps_set(soap, &soap_tmp_ns1__video_fps_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_fps_set(soap, &soap_tmp_ns1__video_fps_set, "ns1:video-fps-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_fps_set(soap, &soap_tmp_ns1__video_fps_set, "ns1:video-fps-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_fps_set(struct soap *soap, int *ret)
{
	struct ns1__video_fps_setResponse *soap_tmp_ns1__video_fps_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_fps_setResponse = soap_get_ns1__video_fps_setResponse(soap, NULL, "ns1:video-fps-setResponse", NULL);
	if (!soap_tmp_ns1__video_fps_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__video_fps_setResponse->ret)
		*ret = *soap_tmp_ns1__video_fps_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_wh_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *w, int *h)
{	if (soap_send_ns1__video_wh_get(soap, soap_endpoint, soap_action, w) || soap_recv_ns1__video_wh_get(soap, h))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_wh_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *w)
{	struct ns1__video_wh_get soap_tmp_ns1__video_wh_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__video_wh_get.w = w;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_wh_get(soap, &soap_tmp_ns1__video_wh_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_wh_get(soap, &soap_tmp_ns1__video_wh_get, "ns1:video-wh-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_wh_get(soap, &soap_tmp_ns1__video_wh_get, "ns1:video-wh-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_wh_get(struct soap *soap, int *h)
{
	struct ns1__video_wh_getResponse *soap_tmp_ns1__video_wh_getResponse;
	if (!h)
		return soap_closesock(soap);
	soap_default_int(soap, h);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_wh_getResponse = soap_get_ns1__video_wh_getResponse(soap, NULL, "ns1:video-wh-getResponse", NULL);
	if (!soap_tmp_ns1__video_wh_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (h && soap_tmp_ns1__video_wh_getResponse->h)
		*h = *soap_tmp_ns1__video_wh_getResponse->h;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h, int *ret)
{	if (soap_send_ns1__video_wh_set(soap, soap_endpoint, soap_action, w, h) || soap_recv_ns1__video_wh_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h)
{	struct ns1__video_wh_set soap_tmp_ns1__video_wh_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__video_wh_set.w = w;
	soap_tmp_ns1__video_wh_set.h = h;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_wh_set(soap, &soap_tmp_ns1__video_wh_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_wh_set(soap, &soap_tmp_ns1__video_wh_set, "ns1:video-wh-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_wh_set(soap, &soap_tmp_ns1__video_wh_set, "ns1:video-wh-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_wh_set(struct soap *soap, int *ret)
{
	struct ns1__video_wh_setResponse *soap_tmp_ns1__video_wh_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_wh_setResponse = soap_get_ns1__video_wh_setResponse(soap, NULL, "ns1:video-wh-setResponse", NULL);
	if (!soap_tmp_ns1__video_wh_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__video_wh_setResponse->ret)
		*ret = *soap_tmp_ns1__video_wh_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_bitrate_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *bitrate_max, int *bitrate_min)
{	if (soap_send_ns1__video_bitrate_get(soap, soap_endpoint, soap_action, bitrate_max) || soap_recv_ns1__video_bitrate_get(soap, bitrate_min))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_bitrate_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *bitrate_max)
{	struct ns1__video_bitrate_get soap_tmp_ns1__video_bitrate_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__video_bitrate_get.bitrate_max = bitrate_max;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_bitrate_get(soap, &soap_tmp_ns1__video_bitrate_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_bitrate_get(soap, &soap_tmp_ns1__video_bitrate_get, "ns1:video-bitrate-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_bitrate_get(soap, &soap_tmp_ns1__video_bitrate_get, "ns1:video-bitrate-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_bitrate_get(struct soap *soap, int *bitrate_min)
{
	struct ns1__video_bitrate_getResponse *soap_tmp_ns1__video_bitrate_getResponse;
	if (!bitrate_min)
		return soap_closesock(soap);
	soap_default_int(soap, bitrate_min);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_bitrate_getResponse = soap_get_ns1__video_bitrate_getResponse(soap, NULL, "ns1:video-bitrate-getResponse", NULL);
	if (!soap_tmp_ns1__video_bitrate_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (bitrate_min && soap_tmp_ns1__video_bitrate_getResponse->bitrate_min)
		*bitrate_min = *soap_tmp_ns1__video_bitrate_getResponse->bitrate_min;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_bitrate_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int bitrate_max, int bitrate_min, int *ret)
{	if (soap_send_ns1__video_bitrate_set(soap, soap_endpoint, soap_action, bitrate_max, bitrate_min) || soap_recv_ns1__video_bitrate_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_bitrate_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int bitrate_max, int bitrate_min)
{	struct ns1__video_bitrate_set soap_tmp_ns1__video_bitrate_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__video_bitrate_set.bitrate_max = bitrate_max;
	soap_tmp_ns1__video_bitrate_set.bitrate_min = bitrate_min;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_bitrate_set(soap, &soap_tmp_ns1__video_bitrate_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_bitrate_set(soap, &soap_tmp_ns1__video_bitrate_set, "ns1:video-bitrate-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_bitrate_set(soap, &soap_tmp_ns1__video_bitrate_set, "ns1:video-bitrate-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_bitrate_set(struct soap *soap, int *ret)
{
	struct ns1__video_bitrate_setResponse *soap_tmp_ns1__video_bitrate_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_bitrate_setResponse = soap_get_ns1__video_bitrate_setResponse(soap, NULL, "ns1:video-bitrate-setResponse", NULL);
	if (!soap_tmp_ns1__video_bitrate_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__video_bitrate_setResponse->ret)
		*ret = *soap_tmp_ns1__video_bitrate_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_interval_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *i_interval)
{	if (soap_send_ns1__video_interval_get(soap, soap_endpoint, soap_action) || soap_recv_ns1__video_interval_get(soap, i_interval))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_interval_get(struct soap *soap, const char *soap_endpoint, const char *soap_action)
{	struct ns1__video_interval_get soap_tmp_ns1__video_interval_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_interval_get(soap, &soap_tmp_ns1__video_interval_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_interval_get(soap, &soap_tmp_ns1__video_interval_get, "ns1:video-interval-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_interval_get(soap, &soap_tmp_ns1__video_interval_get, "ns1:video-interval-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_interval_get(struct soap *soap, int *i_interval)
{
	struct ns1__video_interval_getResponse *soap_tmp_ns1__video_interval_getResponse;
	if (!i_interval)
		return soap_closesock(soap);
	soap_default_int(soap, i_interval);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_interval_getResponse = soap_get_ns1__video_interval_getResponse(soap, NULL, "ns1:video-interval-getResponse", NULL);
	if (!soap_tmp_ns1__video_interval_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (i_interval && soap_tmp_ns1__video_interval_getResponse->i_interval)
		*i_interval = *soap_tmp_ns1__video_interval_getResponse->i_interval;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_interval_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int i_interval, int *ret)
{	if (soap_send_ns1__video_interval_set(soap, soap_endpoint, soap_action, i_interval) || soap_recv_ns1__video_interval_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_interval_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int i_interval)
{	struct ns1__video_interval_set soap_tmp_ns1__video_interval_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__video_interval_set.i_interval = i_interval;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_interval_set(soap, &soap_tmp_ns1__video_interval_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_interval_set(soap, &soap_tmp_ns1__video_interval_set, "ns1:video-interval-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_interval_set(soap, &soap_tmp_ns1__video_interval_set, "ns1:video-interval-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_interval_set(struct soap *soap, int *ret)
{
	struct ns1__video_interval_setResponse *soap_tmp_ns1__video_interval_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_interval_setResponse = soap_get_ns1__video_interval_setResponse(soap, NULL, "ns1:video-interval-setResponse", NULL);
	if (!soap_tmp_ns1__video_interval_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__video_interval_setResponse->ret)
		*ret = *soap_tmp_ns1__video_interval_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__log_info(struct soap *soap, const char *soap_endpoint, const char *soap_action, const char *info)
{	struct ns1__log_info soap_tmp_ns1__log_info;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__log_info.info = info;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__log_info(soap, &soap_tmp_ns1__log_info);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__log_info(soap, &soap_tmp_ns1__log_info, "ns1:log-info", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__log_info(soap, &soap_tmp_ns1__log_info, "ns1:log-info", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__log_info(struct soap *soap, struct ns1__log_info *_param_1)
{
	soap_default_ns1__log_info(soap, _param_1);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__log_info(soap, _param_1, "ns1:log-info", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_OK;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__status_notify(struct soap *soap, const char *soap_endpoint, const char *soap_action, const char *info)
{	struct ns1__status_notify soap_tmp_ns1__status_notify;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__status_notify.info = info;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__status_notify(soap, &soap_tmp_ns1__status_notify);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__status_notify(soap, &soap_tmp_ns1__status_notify, "ns1:status-notify", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__status_notify(soap, &soap_tmp_ns1__status_notify, "ns1:status-notify", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__status_notify(struct soap *soap, struct ns1__status_notify *_param_1)
{
	soap_default_ns1__status_notify(soap, _param_1);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__status_notify(soap, _param_1, "ns1:status-notify", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_OK;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len, int *ret)
{	if (soap_send_ns1__video_cfg_set(soap, soap_endpoint, soap_action, cfg_data, len) || soap_recv_ns1__video_cfg_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len)
{	struct ns1__video_cfg_set soap_tmp_ns1__video_cfg_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__video_cfg_set.cfg_data = cfg_data;
	soap_tmp_ns1__video_cfg_set.len = len;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_cfg_set(soap, &soap_tmp_ns1__video_cfg_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_cfg_set(soap, &soap_tmp_ns1__video_cfg_set, "ns1:video-cfg-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_cfg_set(soap, &soap_tmp_ns1__video_cfg_set, "ns1:video-cfg-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_cfg_set(struct soap *soap, int *ret)
{
	struct ns1__video_cfg_setResponse *soap_tmp_ns1__video_cfg_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_cfg_setResponse = soap_get_ns1__video_cfg_setResponse(soap, NULL, "ns1:video-cfg-setResponse", NULL);
	if (!soap_tmp_ns1__video_cfg_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__video_cfg_setResponse->ret)
		*ret = *soap_tmp_ns1__video_cfg_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **cfg_data)
{	if (soap_send_ns1__video_cfg_get(soap, soap_endpoint, soap_action) || soap_recv_ns1__video_cfg_get(soap, cfg_data))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action)
{	struct ns1__video_cfg_get soap_tmp_ns1__video_cfg_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_cfg_get(soap, &soap_tmp_ns1__video_cfg_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_cfg_get(soap, &soap_tmp_ns1__video_cfg_get, "ns1:video-cfg-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_cfg_get(soap, &soap_tmp_ns1__video_cfg_get, "ns1:video-cfg-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_cfg_get(struct soap *soap, char **cfg_data)
{
	struct ns1__video_cfg_getResponse *soap_tmp_ns1__video_cfg_getResponse;
	if (!cfg_data)
		return soap_closesock(soap);
	*cfg_data = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__video_cfg_getResponse = soap_get_ns1__video_cfg_getResponse(soap, NULL, "ns1:video-cfg-getResponse", NULL);
	if (!soap_tmp_ns1__video_cfg_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (cfg_data && soap_tmp_ns1__video_cfg_getResponse->cfg_data)
		*cfg_data = *soap_tmp_ns1__video_cfg_getResponse->cfg_data;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len, int *ret)
{	if (soap_send_ns1__audio_cfg_set(soap, soap_endpoint, soap_action, cfg_data, len) || soap_recv_ns1__audio_cfg_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len)
{	struct ns1__audio_cfg_set soap_tmp_ns1__audio_cfg_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__audio_cfg_set.cfg_data = cfg_data;
	soap_tmp_ns1__audio_cfg_set.len = len;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_cfg_set(soap, &soap_tmp_ns1__audio_cfg_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_cfg_set(soap, &soap_tmp_ns1__audio_cfg_set, "ns1:audio-cfg-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_cfg_set(soap, &soap_tmp_ns1__audio_cfg_set, "ns1:audio-cfg-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_cfg_set(struct soap *soap, int *ret)
{
	struct ns1__audio_cfg_setResponse *soap_tmp_ns1__audio_cfg_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__audio_cfg_setResponse = soap_get_ns1__audio_cfg_setResponse(soap, NULL, "ns1:audio-cfg-setResponse", NULL);
	if (!soap_tmp_ns1__audio_cfg_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__audio_cfg_setResponse->ret)
		*ret = *soap_tmp_ns1__audio_cfg_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **cfg_data)
{	if (soap_send_ns1__audio_cfg_get(soap, soap_endpoint, soap_action) || soap_recv_ns1__audio_cfg_get(soap, cfg_data))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action)
{	struct ns1__audio_cfg_get soap_tmp_ns1__audio_cfg_get;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_cfg_get(soap, &soap_tmp_ns1__audio_cfg_get);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_cfg_get(soap, &soap_tmp_ns1__audio_cfg_get, "ns1:audio-cfg-get", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_cfg_get(soap, &soap_tmp_ns1__audio_cfg_get, "ns1:audio-cfg-get", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_cfg_get(struct soap *soap, char **cfg_data)
{
	struct ns1__audio_cfg_getResponse *soap_tmp_ns1__audio_cfg_getResponse;
	if (!cfg_data)
		return soap_closesock(soap);
	*cfg_data = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__audio_cfg_getResponse = soap_get_ns1__audio_cfg_getResponse(soap, NULL, "ns1:audio-cfg-getResponse", NULL);
	if (!soap_tmp_ns1__audio_cfg_getResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (cfg_data && soap_tmp_ns1__audio_cfg_getResponse->cfg_data)
		*cfg_data = *soap_tmp_ns1__audio_cfg_getResponse->cfg_data;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__osd_text_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *text_data, int len, int *ret)
{	if (soap_send_ns1__osd_text_set(soap, soap_endpoint, soap_action, text_data, len) || soap_recv_ns1__osd_text_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__osd_text_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *text_data, int len)
{	struct ns1__osd_text_set soap_tmp_ns1__osd_text_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__osd_text_set.text_data = text_data;
	soap_tmp_ns1__osd_text_set.len = len;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__osd_text_set(soap, &soap_tmp_ns1__osd_text_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__osd_text_set(soap, &soap_tmp_ns1__osd_text_set, "ns1:osd-text-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__osd_text_set(soap, &soap_tmp_ns1__osd_text_set, "ns1:osd-text-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__osd_text_set(struct soap *soap, int *ret)
{
	struct ns1__osd_text_setResponse *soap_tmp_ns1__osd_text_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__osd_text_setResponse = soap_get_ns1__osd_text_setResponse(soap, NULL, "ns1:osd-text-setResponse", NULL);
	if (!soap_tmp_ns1__osd_text_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__osd_text_setResponse->ret)
		*ret = *soap_tmp_ns1__osd_text_setResponse->ret;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__hdmi_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h, int fps, int *ret)
{	if (soap_send_ns1__hdmi_wh_set(soap, soap_endpoint, soap_action, w, h, fps) || soap_recv_ns1__hdmi_wh_set(soap, ret))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__hdmi_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h, int fps)
{	struct ns1__hdmi_wh_set soap_tmp_ns1__hdmi_wh_set;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost/SayHello/";
	soap_tmp_ns1__hdmi_wh_set.w = w;
	soap_tmp_ns1__hdmi_wh_set.h = h;
	soap_tmp_ns1__hdmi_wh_set.fps = fps;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__hdmi_wh_set(soap, &soap_tmp_ns1__hdmi_wh_set);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__hdmi_wh_set(soap, &soap_tmp_ns1__hdmi_wh_set, "ns1:hdmi-wh-set", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__hdmi_wh_set(soap, &soap_tmp_ns1__hdmi_wh_set, "ns1:hdmi-wh-set", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__hdmi_wh_set(struct soap *soap, int *ret)
{
	struct ns1__hdmi_wh_setResponse *soap_tmp_ns1__hdmi_wh_setResponse;
	if (!ret)
		return soap_closesock(soap);
	soap_default_int(soap, ret);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__hdmi_wh_setResponse = soap_get_ns1__hdmi_wh_setResponse(soap, NULL, "ns1:hdmi-wh-setResponse", NULL);
	if (!soap_tmp_ns1__hdmi_wh_setResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ret && soap_tmp_ns1__hdmi_wh_setResponse->ret)
		*ret = *soap_tmp_ns1__hdmi_wh_setResponse->ret;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
