/* soapServer.c
   Generated by gSOAP 2.8.114 for hello.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.114 2024-04-02 08:24:42 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:sayHello"))
		return soap_serve_ns1__sayHello(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:audio-sample-set"))
		return soap_serve_ns1__audio_sample_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:audio-sample-get"))
		return soap_serve_ns1__audio_sample_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:audio-button-status-get"))
		return soap_serve_ns1__audio_button_status_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-fps-get"))
		return soap_serve_ns1__video_fps_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-fps-set"))
		return soap_serve_ns1__video_fps_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-wh-get"))
		return soap_serve_ns1__video_wh_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-wh-set"))
		return soap_serve_ns1__video_wh_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-bitrate-get"))
		return soap_serve_ns1__video_bitrate_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-bitrate-set"))
		return soap_serve_ns1__video_bitrate_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-interval-get"))
		return soap_serve_ns1__video_interval_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-interval-set"))
		return soap_serve_ns1__video_interval_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:log-info"))
		return soap_serve_ns1__log_info(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:status-notify"))
		return soap_serve_ns1__status_notify(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-cfg-set"))
		return soap_serve_ns1__video_cfg_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:video-cfg-get"))
		return soap_serve_ns1__video_cfg_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:audio-cfg-set"))
		return soap_serve_ns1__audio_cfg_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:audio-cfg-get"))
		return soap_serve_ns1__audio_cfg_get(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:osd-text-set"))
		return soap_serve_ns1__osd_text_set(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:hdmi-wh-set"))
		return soap_serve_ns1__hdmi_wh_set(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__sayHello(struct soap *soap)
{	struct ns1__sayHello soap_tmp_ns1__sayHello;
	struct ns1__sayHelloResponse soap_tmp_ns1__sayHelloResponse;
	char * soap_tmp_string;
	soap_default_ns1__sayHelloResponse(soap, &soap_tmp_ns1__sayHelloResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__sayHelloResponse.greeting = &soap_tmp_string;
	soap_default_ns1__sayHello(soap, &soap_tmp_ns1__sayHello);
	if (!soap_get_ns1__sayHello(soap, &soap_tmp_ns1__sayHello, "ns1:sayHello", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__sayHello(soap, soap_tmp_ns1__sayHello.firstName, soap_tmp_ns1__sayHelloResponse.greeting);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns1__sayHelloResponse(soap, &soap_tmp_ns1__sayHelloResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__sayHelloResponse(soap, &soap_tmp_ns1__sayHelloResponse, "ns1:sayHelloResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__sayHelloResponse(soap, &soap_tmp_ns1__sayHelloResponse, "ns1:sayHelloResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_sample_set(struct soap *soap)
{	struct ns1__audio_sample_set soap_tmp_ns1__audio_sample_set;
	struct ns1__audio_sample_setResponse soap_tmp_ns1__audio_sample_setResponse;
	int soap_tmp_int;
	soap_default_ns1__audio_sample_setResponse(soap, &soap_tmp_ns1__audio_sample_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__audio_sample_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__audio_sample_set(soap, &soap_tmp_ns1__audio_sample_set);
	if (!soap_get_ns1__audio_sample_set(soap, &soap_tmp_ns1__audio_sample_set, "ns1:audio-sample-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__audio_sample_set(soap, soap_tmp_ns1__audio_sample_set.sample, soap_tmp_ns1__audio_sample_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_sample_setResponse(soap, &soap_tmp_ns1__audio_sample_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_sample_setResponse(soap, &soap_tmp_ns1__audio_sample_setResponse, "ns1:audio-sample-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_sample_setResponse(soap, &soap_tmp_ns1__audio_sample_setResponse, "ns1:audio-sample-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_sample_get(struct soap *soap)
{	struct ns1__audio_sample_get soap_tmp_ns1__audio_sample_get;
	struct ns1__audio_sample_getResponse soap_tmp_ns1__audio_sample_getResponse;
	int soap_tmp_int;
	soap_default_ns1__audio_sample_getResponse(soap, &soap_tmp_ns1__audio_sample_getResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__audio_sample_getResponse.sample = &soap_tmp_int;
	soap_default_ns1__audio_sample_get(soap, &soap_tmp_ns1__audio_sample_get);
	if (!soap_get_ns1__audio_sample_get(soap, &soap_tmp_ns1__audio_sample_get, "ns1:audio-sample-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__audio_sample_get(soap, soap_tmp_ns1__audio_sample_getResponse.sample);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_sample_getResponse(soap, &soap_tmp_ns1__audio_sample_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_sample_getResponse(soap, &soap_tmp_ns1__audio_sample_getResponse, "ns1:audio-sample-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_sample_getResponse(soap, &soap_tmp_ns1__audio_sample_getResponse, "ns1:audio-sample-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_button_status_get(struct soap *soap)
{	struct ns1__audio_button_status_get soap_tmp_ns1__audio_button_status_get;
	struct ns1__audio_button_status_getResponse soap_tmp_ns1__audio_button_status_getResponse;
	int soap_tmp_int;
	soap_default_ns1__audio_button_status_getResponse(soap, &soap_tmp_ns1__audio_button_status_getResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__audio_button_status_getResponse.status = &soap_tmp_int;
	soap_default_ns1__audio_button_status_get(soap, &soap_tmp_ns1__audio_button_status_get);
	if (!soap_get_ns1__audio_button_status_get(soap, &soap_tmp_ns1__audio_button_status_get, "ns1:audio-button-status-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__audio_button_status_get(soap, soap_tmp_ns1__audio_button_status_getResponse.status);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_button_status_getResponse(soap, &soap_tmp_ns1__audio_button_status_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_button_status_getResponse(soap, &soap_tmp_ns1__audio_button_status_getResponse, "ns1:audio-button-status-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_button_status_getResponse(soap, &soap_tmp_ns1__audio_button_status_getResponse, "ns1:audio-button-status-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_fps_get(struct soap *soap)
{	struct ns1__video_fps_get soap_tmp_ns1__video_fps_get;
	struct ns1__video_fps_getResponse soap_tmp_ns1__video_fps_getResponse;
	int soap_tmp_int;
	soap_default_ns1__video_fps_getResponse(soap, &soap_tmp_ns1__video_fps_getResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_fps_getResponse.fps = &soap_tmp_int;
	soap_default_ns1__video_fps_get(soap, &soap_tmp_ns1__video_fps_get);
	if (!soap_get_ns1__video_fps_get(soap, &soap_tmp_ns1__video_fps_get, "ns1:video-fps-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_fps_get(soap, soap_tmp_ns1__video_fps_getResponse.fps);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_fps_getResponse(soap, &soap_tmp_ns1__video_fps_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_fps_getResponse(soap, &soap_tmp_ns1__video_fps_getResponse, "ns1:video-fps-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_fps_getResponse(soap, &soap_tmp_ns1__video_fps_getResponse, "ns1:video-fps-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_fps_set(struct soap *soap)
{	struct ns1__video_fps_set soap_tmp_ns1__video_fps_set;
	struct ns1__video_fps_setResponse soap_tmp_ns1__video_fps_setResponse;
	int soap_tmp_int;
	soap_default_ns1__video_fps_setResponse(soap, &soap_tmp_ns1__video_fps_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_fps_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__video_fps_set(soap, &soap_tmp_ns1__video_fps_set);
	if (!soap_get_ns1__video_fps_set(soap, &soap_tmp_ns1__video_fps_set, "ns1:video-fps-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_fps_set(soap, soap_tmp_ns1__video_fps_set.fps, soap_tmp_ns1__video_fps_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_fps_setResponse(soap, &soap_tmp_ns1__video_fps_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_fps_setResponse(soap, &soap_tmp_ns1__video_fps_setResponse, "ns1:video-fps-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_fps_setResponse(soap, &soap_tmp_ns1__video_fps_setResponse, "ns1:video-fps-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_wh_get(struct soap *soap)
{	struct ns1__video_wh_get soap_tmp_ns1__video_wh_get;
	struct ns1__video_wh_getResponse soap_tmp_ns1__video_wh_getResponse;
	int soap_tmp_int;
	soap_default_ns1__video_wh_getResponse(soap, &soap_tmp_ns1__video_wh_getResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_wh_getResponse.h = &soap_tmp_int;
	soap_default_ns1__video_wh_get(soap, &soap_tmp_ns1__video_wh_get);
	if (!soap_get_ns1__video_wh_get(soap, &soap_tmp_ns1__video_wh_get, "ns1:video-wh-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_wh_get(soap, soap_tmp_ns1__video_wh_get.w, soap_tmp_ns1__video_wh_getResponse.h);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_wh_getResponse(soap, &soap_tmp_ns1__video_wh_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_wh_getResponse(soap, &soap_tmp_ns1__video_wh_getResponse, "ns1:video-wh-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_wh_getResponse(soap, &soap_tmp_ns1__video_wh_getResponse, "ns1:video-wh-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_wh_set(struct soap *soap)
{	struct ns1__video_wh_set soap_tmp_ns1__video_wh_set;
	struct ns1__video_wh_setResponse soap_tmp_ns1__video_wh_setResponse;
	int soap_tmp_int;
	soap_default_ns1__video_wh_setResponse(soap, &soap_tmp_ns1__video_wh_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_wh_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__video_wh_set(soap, &soap_tmp_ns1__video_wh_set);
	if (!soap_get_ns1__video_wh_set(soap, &soap_tmp_ns1__video_wh_set, "ns1:video-wh-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_wh_set(soap, soap_tmp_ns1__video_wh_set.w, soap_tmp_ns1__video_wh_set.h, soap_tmp_ns1__video_wh_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_wh_setResponse(soap, &soap_tmp_ns1__video_wh_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_wh_setResponse(soap, &soap_tmp_ns1__video_wh_setResponse, "ns1:video-wh-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_wh_setResponse(soap, &soap_tmp_ns1__video_wh_setResponse, "ns1:video-wh-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_bitrate_get(struct soap *soap)
{	struct ns1__video_bitrate_get soap_tmp_ns1__video_bitrate_get;
	struct ns1__video_bitrate_getResponse soap_tmp_ns1__video_bitrate_getResponse;
	int soap_tmp_int;
	soap_default_ns1__video_bitrate_getResponse(soap, &soap_tmp_ns1__video_bitrate_getResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_bitrate_getResponse.bitrate_min = &soap_tmp_int;
	soap_default_ns1__video_bitrate_get(soap, &soap_tmp_ns1__video_bitrate_get);
	if (!soap_get_ns1__video_bitrate_get(soap, &soap_tmp_ns1__video_bitrate_get, "ns1:video-bitrate-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_bitrate_get(soap, soap_tmp_ns1__video_bitrate_get.bitrate_max, soap_tmp_ns1__video_bitrate_getResponse.bitrate_min);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_bitrate_getResponse(soap, &soap_tmp_ns1__video_bitrate_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_bitrate_getResponse(soap, &soap_tmp_ns1__video_bitrate_getResponse, "ns1:video-bitrate-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_bitrate_getResponse(soap, &soap_tmp_ns1__video_bitrate_getResponse, "ns1:video-bitrate-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_bitrate_set(struct soap *soap)
{	struct ns1__video_bitrate_set soap_tmp_ns1__video_bitrate_set;
	struct ns1__video_bitrate_setResponse soap_tmp_ns1__video_bitrate_setResponse;
	int soap_tmp_int;
	soap_default_ns1__video_bitrate_setResponse(soap, &soap_tmp_ns1__video_bitrate_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_bitrate_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__video_bitrate_set(soap, &soap_tmp_ns1__video_bitrate_set);
	if (!soap_get_ns1__video_bitrate_set(soap, &soap_tmp_ns1__video_bitrate_set, "ns1:video-bitrate-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_bitrate_set(soap, soap_tmp_ns1__video_bitrate_set.bitrate_max, soap_tmp_ns1__video_bitrate_set.bitrate_min, soap_tmp_ns1__video_bitrate_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_bitrate_setResponse(soap, &soap_tmp_ns1__video_bitrate_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_bitrate_setResponse(soap, &soap_tmp_ns1__video_bitrate_setResponse, "ns1:video-bitrate-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_bitrate_setResponse(soap, &soap_tmp_ns1__video_bitrate_setResponse, "ns1:video-bitrate-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_interval_get(struct soap *soap)
{	struct ns1__video_interval_get soap_tmp_ns1__video_interval_get;
	struct ns1__video_interval_getResponse soap_tmp_ns1__video_interval_getResponse;
	int soap_tmp_int;
	soap_default_ns1__video_interval_getResponse(soap, &soap_tmp_ns1__video_interval_getResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_interval_getResponse.i_interval = &soap_tmp_int;
	soap_default_ns1__video_interval_get(soap, &soap_tmp_ns1__video_interval_get);
	if (!soap_get_ns1__video_interval_get(soap, &soap_tmp_ns1__video_interval_get, "ns1:video-interval-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_interval_get(soap, soap_tmp_ns1__video_interval_getResponse.i_interval);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_interval_getResponse(soap, &soap_tmp_ns1__video_interval_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_interval_getResponse(soap, &soap_tmp_ns1__video_interval_getResponse, "ns1:video-interval-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_interval_getResponse(soap, &soap_tmp_ns1__video_interval_getResponse, "ns1:video-interval-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_interval_set(struct soap *soap)
{	struct ns1__video_interval_set soap_tmp_ns1__video_interval_set;
	struct ns1__video_interval_setResponse soap_tmp_ns1__video_interval_setResponse;
	int soap_tmp_int;
	soap_default_ns1__video_interval_setResponse(soap, &soap_tmp_ns1__video_interval_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_interval_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__video_interval_set(soap, &soap_tmp_ns1__video_interval_set);
	if (!soap_get_ns1__video_interval_set(soap, &soap_tmp_ns1__video_interval_set, "ns1:video-interval-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_interval_set(soap, soap_tmp_ns1__video_interval_set.i_interval, soap_tmp_ns1__video_interval_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_interval_setResponse(soap, &soap_tmp_ns1__video_interval_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_interval_setResponse(soap, &soap_tmp_ns1__video_interval_setResponse, "ns1:video-interval-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_interval_setResponse(soap, &soap_tmp_ns1__video_interval_setResponse, "ns1:video-interval-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__log_info(struct soap *soap)
{	struct ns1__log_info soap_tmp_ns1__log_info;
	soap_default_ns1__log_info(soap, &soap_tmp_ns1__log_info);
	if (!soap_get_ns1__log_info(soap, &soap_tmp_ns1__log_info, "ns1:log-info", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__log_info(soap, soap_tmp_ns1__log_info.info);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__status_notify(struct soap *soap)
{	struct ns1__status_notify soap_tmp_ns1__status_notify;
	soap_default_ns1__status_notify(soap, &soap_tmp_ns1__status_notify);
	if (!soap_get_ns1__status_notify(soap, &soap_tmp_ns1__status_notify, "ns1:status-notify", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__status_notify(soap, soap_tmp_ns1__status_notify.info);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_cfg_set(struct soap *soap)
{	struct ns1__video_cfg_set soap_tmp_ns1__video_cfg_set;
	struct ns1__video_cfg_setResponse soap_tmp_ns1__video_cfg_setResponse;
	int soap_tmp_int;
	soap_default_ns1__video_cfg_setResponse(soap, &soap_tmp_ns1__video_cfg_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__video_cfg_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__video_cfg_set(soap, &soap_tmp_ns1__video_cfg_set);
	if (!soap_get_ns1__video_cfg_set(soap, &soap_tmp_ns1__video_cfg_set, "ns1:video-cfg-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_cfg_set(soap, soap_tmp_ns1__video_cfg_set.cfg_data, soap_tmp_ns1__video_cfg_set.len, soap_tmp_ns1__video_cfg_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_cfg_setResponse(soap, &soap_tmp_ns1__video_cfg_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_cfg_setResponse(soap, &soap_tmp_ns1__video_cfg_setResponse, "ns1:video-cfg-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_cfg_setResponse(soap, &soap_tmp_ns1__video_cfg_setResponse, "ns1:video-cfg-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_cfg_get(struct soap *soap)
{	struct ns1__video_cfg_get soap_tmp_ns1__video_cfg_get;
	struct ns1__video_cfg_getResponse soap_tmp_ns1__video_cfg_getResponse;
	char * soap_tmp_string;
	soap_default_ns1__video_cfg_getResponse(soap, &soap_tmp_ns1__video_cfg_getResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__video_cfg_getResponse.cfg_data = &soap_tmp_string;
	soap_default_ns1__video_cfg_get(soap, &soap_tmp_ns1__video_cfg_get);
	if (!soap_get_ns1__video_cfg_get(soap, &soap_tmp_ns1__video_cfg_get, "ns1:video-cfg-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__video_cfg_get(soap, soap_tmp_ns1__video_cfg_getResponse.cfg_data);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__video_cfg_getResponse(soap, &soap_tmp_ns1__video_cfg_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__video_cfg_getResponse(soap, &soap_tmp_ns1__video_cfg_getResponse, "ns1:video-cfg-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__video_cfg_getResponse(soap, &soap_tmp_ns1__video_cfg_getResponse, "ns1:video-cfg-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_cfg_set(struct soap *soap)
{	struct ns1__audio_cfg_set soap_tmp_ns1__audio_cfg_set;
	struct ns1__audio_cfg_setResponse soap_tmp_ns1__audio_cfg_setResponse;
	int soap_tmp_int;
	soap_default_ns1__audio_cfg_setResponse(soap, &soap_tmp_ns1__audio_cfg_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__audio_cfg_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__audio_cfg_set(soap, &soap_tmp_ns1__audio_cfg_set);
	if (!soap_get_ns1__audio_cfg_set(soap, &soap_tmp_ns1__audio_cfg_set, "ns1:audio-cfg-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__audio_cfg_set(soap, soap_tmp_ns1__audio_cfg_set.cfg_data, soap_tmp_ns1__audio_cfg_set.len, soap_tmp_ns1__audio_cfg_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_cfg_setResponse(soap, &soap_tmp_ns1__audio_cfg_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_cfg_setResponse(soap, &soap_tmp_ns1__audio_cfg_setResponse, "ns1:audio-cfg-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_cfg_setResponse(soap, &soap_tmp_ns1__audio_cfg_setResponse, "ns1:audio-cfg-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_cfg_get(struct soap *soap)
{	struct ns1__audio_cfg_get soap_tmp_ns1__audio_cfg_get;
	struct ns1__audio_cfg_getResponse soap_tmp_ns1__audio_cfg_getResponse;
	char * soap_tmp_string;
	soap_default_ns1__audio_cfg_getResponse(soap, &soap_tmp_ns1__audio_cfg_getResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__audio_cfg_getResponse.cfg_data = &soap_tmp_string;
	soap_default_ns1__audio_cfg_get(soap, &soap_tmp_ns1__audio_cfg_get);
	if (!soap_get_ns1__audio_cfg_get(soap, &soap_tmp_ns1__audio_cfg_get, "ns1:audio-cfg-get", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__audio_cfg_get(soap, soap_tmp_ns1__audio_cfg_getResponse.cfg_data);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__audio_cfg_getResponse(soap, &soap_tmp_ns1__audio_cfg_getResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__audio_cfg_getResponse(soap, &soap_tmp_ns1__audio_cfg_getResponse, "ns1:audio-cfg-getResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__audio_cfg_getResponse(soap, &soap_tmp_ns1__audio_cfg_getResponse, "ns1:audio-cfg-getResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__osd_text_set(struct soap *soap)
{	struct ns1__osd_text_set soap_tmp_ns1__osd_text_set;
	struct ns1__osd_text_setResponse soap_tmp_ns1__osd_text_setResponse;
	int soap_tmp_int;
	soap_default_ns1__osd_text_setResponse(soap, &soap_tmp_ns1__osd_text_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__osd_text_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__osd_text_set(soap, &soap_tmp_ns1__osd_text_set);
	if (!soap_get_ns1__osd_text_set(soap, &soap_tmp_ns1__osd_text_set, "ns1:osd-text-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__osd_text_set(soap, soap_tmp_ns1__osd_text_set.text_data, soap_tmp_ns1__osd_text_set.len, soap_tmp_ns1__osd_text_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__osd_text_setResponse(soap, &soap_tmp_ns1__osd_text_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__osd_text_setResponse(soap, &soap_tmp_ns1__osd_text_setResponse, "ns1:osd-text-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__osd_text_setResponse(soap, &soap_tmp_ns1__osd_text_setResponse, "ns1:osd-text-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__hdmi_wh_set(struct soap *soap)
{	struct ns1__hdmi_wh_set soap_tmp_ns1__hdmi_wh_set;
	struct ns1__hdmi_wh_setResponse soap_tmp_ns1__hdmi_wh_setResponse;
	int soap_tmp_int;
	soap_default_ns1__hdmi_wh_setResponse(soap, &soap_tmp_ns1__hdmi_wh_setResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__hdmi_wh_setResponse.ret = &soap_tmp_int;
	soap_default_ns1__hdmi_wh_set(soap, &soap_tmp_ns1__hdmi_wh_set);
	if (!soap_get_ns1__hdmi_wh_set(soap, &soap_tmp_ns1__hdmi_wh_set, "ns1:hdmi-wh-set", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__hdmi_wh_set(soap, soap_tmp_ns1__hdmi_wh_set.w, soap_tmp_ns1__hdmi_wh_set.h, soap_tmp_ns1__hdmi_wh_set.fps, soap_tmp_ns1__hdmi_wh_setResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__hdmi_wh_setResponse(soap, &soap_tmp_ns1__hdmi_wh_setResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__hdmi_wh_setResponse(soap, &soap_tmp_ns1__hdmi_wh_setResponse, "ns1:hdmi-wh-setResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__hdmi_wh_setResponse(soap, &soap_tmp_ns1__hdmi_wh_setResponse, "ns1:hdmi-wh-setResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
