/* soapStub.h
   Generated by gSOAP 2.8.114 for hello.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/


#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208114
# error "GSOAP VERSION 208114 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns1__sayHelloResponse;	/* hello.h:235 */
struct ns1__sayHello;	/* hello.h:235 */
struct ns1__audio_sample_setResponse;	/* hello.h:239 */
struct ns1__audio_sample_set;	/* hello.h:239 */
struct ns1__audio_sample_getResponse;	/* hello.h:242 */
struct ns1__audio_sample_get;	/* hello.h:242 */
struct ns1__audio_button_status_getResponse;	/* hello.h:245 */
struct ns1__audio_button_status_get;	/* hello.h:245 */
struct ns1__video_fps_getResponse;	/* hello.h:251 */
struct ns1__video_fps_get;	/* hello.h:251 */
struct ns1__video_fps_setResponse;	/* hello.h:253 */
struct ns1__video_fps_set;	/* hello.h:253 */
struct ns1__video_wh_getResponse;	/* hello.h:256 */
struct ns1__video_wh_get;	/* hello.h:256 */
struct ns1__video_wh_setResponse;	/* hello.h:258 */
struct ns1__video_wh_set;	/* hello.h:258 */
struct ns1__video_bitrate_getResponse;	/* hello.h:261 */
struct ns1__video_bitrate_get;	/* hello.h:261 */
struct ns1__video_bitrate_setResponse;	/* hello.h:263 */
struct ns1__video_bitrate_set;	/* hello.h:263 */
struct ns1__video_interval_getResponse;	/* hello.h:266 */
struct ns1__video_interval_get;	/* hello.h:266 */
struct ns1__video_interval_setResponse;	/* hello.h:268 */
struct ns1__video_interval_set;	/* hello.h:268 */
struct ns1__log_info;	/* hello.h:271 */
struct ns1__status_notify;	/* hello.h:274 */
struct ns1__video_cfg_setResponse;	/* hello.h:277 */
struct ns1__video_cfg_set;	/* hello.h:277 */
struct ns1__video_cfg_getResponse;	/* hello.h:280 */
struct ns1__video_cfg_get;	/* hello.h:280 */
struct ns1__audio_cfg_setResponse;	/* hello.h:283 */
struct ns1__audio_cfg_set;	/* hello.h:283 */
struct ns1__audio_cfg_getResponse;	/* hello.h:286 */
struct ns1__audio_cfg_get;	/* hello.h:286 */
struct ns1__osd_text_setResponse;	/* hello.h:289 */
struct ns1__osd_text_set;	/* hello.h:289 */
struct ns1__hdmi_wh_setResponse;	/* hello.h:291 */
struct ns1__hdmi_wh_set;	/* hello.h:291 */

/* hello.h:235 */
#ifndef SOAP_TYPE_ns1__sayHelloResponse
#define SOAP_TYPE_ns1__sayHelloResponse (9)
/* complex XML schema type 'ns1:sayHelloResponse': */
struct ns1__sayHelloResponse {
        /** Optional element 'greeting' of XML schema type 'xsd:string' */
        char **greeting;
};
#endif

/* hello.h:235 */
#ifndef SOAP_TYPE_ns1__sayHello
#define SOAP_TYPE_ns1__sayHello (10)
/* complex XML schema type 'ns1:sayHello': */
struct ns1__sayHello {
        /** Optional element 'firstName' of XML schema type 'xsd:string' */
        char *firstName;
};
#endif

/* hello.h:239 */
#ifndef SOAP_TYPE_ns1__audio_sample_setResponse
#define SOAP_TYPE_ns1__audio_sample_setResponse (13)
/* complex XML schema type 'ns1:audio-sample-setResponse': */
struct ns1__audio_sample_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:239 */
#ifndef SOAP_TYPE_ns1__audio_sample_set
#define SOAP_TYPE_ns1__audio_sample_set (14)
/* complex XML schema type 'ns1:audio-sample-set': */
struct ns1__audio_sample_set {
        /** Required element 'sample' of XML schema type 'xsd:int' */
        int sample;
};
#endif

/* hello.h:242 */
#ifndef SOAP_TYPE_ns1__audio_sample_getResponse
#define SOAP_TYPE_ns1__audio_sample_getResponse (16)
/* complex XML schema type 'ns1:audio-sample-getResponse': */
struct ns1__audio_sample_getResponse {
        /** Optional element 'sample' of XML schema type 'xsd:int' */
        int *sample;
};
#endif

/* hello.h:242 */
#ifndef SOAP_TYPE_ns1__audio_sample_get
#define SOAP_TYPE_ns1__audio_sample_get (17)
/* complex XML schema type 'ns1:audio-sample-get': */
struct ns1__audio_sample_get {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* hello.h:245 */
#ifndef SOAP_TYPE_ns1__audio_button_status_getResponse
#define SOAP_TYPE_ns1__audio_button_status_getResponse (19)
/* complex XML schema type 'ns1:audio-button-status-getResponse': */
struct ns1__audio_button_status_getResponse {
        /** Optional element 'status' of XML schema type 'xsd:int' */
        int *status;
};
#endif

/* hello.h:245 */
#ifndef SOAP_TYPE_ns1__audio_button_status_get
#define SOAP_TYPE_ns1__audio_button_status_get (20)
/* complex XML schema type 'ns1:audio-button-status-get': */
struct ns1__audio_button_status_get {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* hello.h:251 */
#ifndef SOAP_TYPE_ns1__video_fps_getResponse
#define SOAP_TYPE_ns1__video_fps_getResponse (22)
/* complex XML schema type 'ns1:video-fps-getResponse': */
struct ns1__video_fps_getResponse {
        /** Optional element 'fps' of XML schema type 'xsd:int' */
        int *fps;
};
#endif

/* hello.h:251 */
#ifndef SOAP_TYPE_ns1__video_fps_get
#define SOAP_TYPE_ns1__video_fps_get (23)
/* complex XML schema type 'ns1:video-fps-get': */
struct ns1__video_fps_get {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* hello.h:253 */
#ifndef SOAP_TYPE_ns1__video_fps_setResponse
#define SOAP_TYPE_ns1__video_fps_setResponse (25)
/* complex XML schema type 'ns1:video-fps-setResponse': */
struct ns1__video_fps_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:253 */
#ifndef SOAP_TYPE_ns1__video_fps_set
#define SOAP_TYPE_ns1__video_fps_set (26)
/* complex XML schema type 'ns1:video-fps-set': */
struct ns1__video_fps_set {
        /** Required element 'fps' of XML schema type 'xsd:int' */
        int fps;
};
#endif

/* hello.h:256 */
#ifndef SOAP_TYPE_ns1__video_wh_getResponse
#define SOAP_TYPE_ns1__video_wh_getResponse (28)
/* complex XML schema type 'ns1:video-wh-getResponse': */
struct ns1__video_wh_getResponse {
        /** Optional element 'h' of XML schema type 'xsd:int' */
        int *h;
};
#endif

/* hello.h:256 */
#ifndef SOAP_TYPE_ns1__video_wh_get
#define SOAP_TYPE_ns1__video_wh_get (29)
/* complex XML schema type 'ns1:video-wh-get': */
struct ns1__video_wh_get {
        /** Optional element 'w' of XML schema type 'xsd:int' */
        int *w;
};
#endif

/* hello.h:258 */
#ifndef SOAP_TYPE_ns1__video_wh_setResponse
#define SOAP_TYPE_ns1__video_wh_setResponse (31)
/* complex XML schema type 'ns1:video-wh-setResponse': */
struct ns1__video_wh_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:258 */
#ifndef SOAP_TYPE_ns1__video_wh_set
#define SOAP_TYPE_ns1__video_wh_set (32)
/* complex XML schema type 'ns1:video-wh-set': */
struct ns1__video_wh_set {
        /** Required element 'w' of XML schema type 'xsd:int' */
        int w;
        /** Required element 'h' of XML schema type 'xsd:int' */
        int h;
};
#endif

/* hello.h:261 */
#ifndef SOAP_TYPE_ns1__video_bitrate_getResponse
#define SOAP_TYPE_ns1__video_bitrate_getResponse (34)
/* complex XML schema type 'ns1:video-bitrate-getResponse': */
struct ns1__video_bitrate_getResponse {
        /** Optional element 'bitrate-min' of XML schema type 'xsd:int' */
        int *bitrate_min;
};
#endif

/* hello.h:261 */
#ifndef SOAP_TYPE_ns1__video_bitrate_get
#define SOAP_TYPE_ns1__video_bitrate_get (35)
/* complex XML schema type 'ns1:video-bitrate-get': */
struct ns1__video_bitrate_get {
        /** Optional element 'bitrate-max' of XML schema type 'xsd:int' */
        int *bitrate_max;
};
#endif

/* hello.h:263 */
#ifndef SOAP_TYPE_ns1__video_bitrate_setResponse
#define SOAP_TYPE_ns1__video_bitrate_setResponse (37)
/* complex XML schema type 'ns1:video-bitrate-setResponse': */
struct ns1__video_bitrate_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:263 */
#ifndef SOAP_TYPE_ns1__video_bitrate_set
#define SOAP_TYPE_ns1__video_bitrate_set (38)
/* complex XML schema type 'ns1:video-bitrate-set': */
struct ns1__video_bitrate_set {
        /** Required element 'bitrate-max' of XML schema type 'xsd:int' */
        int bitrate_max;
        /** Required element 'bitrate-min' of XML schema type 'xsd:int' */
        int bitrate_min;
};
#endif

/* hello.h:266 */
#ifndef SOAP_TYPE_ns1__video_interval_getResponse
#define SOAP_TYPE_ns1__video_interval_getResponse (40)
/* complex XML schema type 'ns1:video-interval-getResponse': */
struct ns1__video_interval_getResponse {
        /** Optional element 'i-interval' of XML schema type 'xsd:int' */
        int *i_interval;
};
#endif

/* hello.h:266 */
#ifndef SOAP_TYPE_ns1__video_interval_get
#define SOAP_TYPE_ns1__video_interval_get (41)
/* complex XML schema type 'ns1:video-interval-get': */
struct ns1__video_interval_get {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* hello.h:268 */
#ifndef SOAP_TYPE_ns1__video_interval_setResponse
#define SOAP_TYPE_ns1__video_interval_setResponse (43)
/* complex XML schema type 'ns1:video-interval-setResponse': */
struct ns1__video_interval_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:268 */
#ifndef SOAP_TYPE_ns1__video_interval_set
#define SOAP_TYPE_ns1__video_interval_set (44)
/* complex XML schema type 'ns1:video-interval-set': */
struct ns1__video_interval_set {
        /** Required element 'i-interval' of XML schema type 'xsd:int' */
        int i_interval;
};
#endif

/* hello.h:271 */
#ifndef SOAP_TYPE_ns1__log_info
#define SOAP_TYPE_ns1__log_info (47)
/* complex XML schema type 'ns1:log-info': */
struct ns1__log_info {
        /** Optional element 'info' of XML schema type 'xsd:string' */
        const char *info;
};
#endif

/* hello.h:274 */
#ifndef SOAP_TYPE_ns1__status_notify
#define SOAP_TYPE_ns1__status_notify (49)
/* complex XML schema type 'ns1:status-notify': */
struct ns1__status_notify {
        /** Optional element 'info' of XML schema type 'xsd:string' */
        const char *info;
};
#endif

/* hello.h:277 */
#ifndef SOAP_TYPE_ns1__video_cfg_setResponse
#define SOAP_TYPE_ns1__video_cfg_setResponse (51)
/* complex XML schema type 'ns1:video-cfg-setResponse': */
struct ns1__video_cfg_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:277 */
#ifndef SOAP_TYPE_ns1__video_cfg_set
#define SOAP_TYPE_ns1__video_cfg_set (52)
/* complex XML schema type 'ns1:video-cfg-set': */
struct ns1__video_cfg_set {
        /** Optional element 'cfg-data' of XML schema type 'xsd:string' */
        char *cfg_data;
        /** Required element 'len' of XML schema type 'xsd:int' */
        int len;
};
#endif

/* hello.h:280 */
#ifndef SOAP_TYPE_ns1__video_cfg_getResponse
#define SOAP_TYPE_ns1__video_cfg_getResponse (54)
/* complex XML schema type 'ns1:video-cfg-getResponse': */
struct ns1__video_cfg_getResponse {
        /** Optional element 'cfg-data' of XML schema type 'xsd:string' */
        char **cfg_data;
};
#endif

/* hello.h:280 */
#ifndef SOAP_TYPE_ns1__video_cfg_get
#define SOAP_TYPE_ns1__video_cfg_get (55)
/* complex XML schema type 'ns1:video-cfg-get': */
struct ns1__video_cfg_get {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* hello.h:283 */
#ifndef SOAP_TYPE_ns1__audio_cfg_setResponse
#define SOAP_TYPE_ns1__audio_cfg_setResponse (57)
/* complex XML schema type 'ns1:audio-cfg-setResponse': */
struct ns1__audio_cfg_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:283 */
#ifndef SOAP_TYPE_ns1__audio_cfg_set
#define SOAP_TYPE_ns1__audio_cfg_set (58)
/* complex XML schema type 'ns1:audio-cfg-set': */
struct ns1__audio_cfg_set {
        /** Optional element 'cfg-data' of XML schema type 'xsd:string' */
        char *cfg_data;
        /** Required element 'len' of XML schema type 'xsd:int' */
        int len;
};
#endif

/* hello.h:286 */
#ifndef SOAP_TYPE_ns1__audio_cfg_getResponse
#define SOAP_TYPE_ns1__audio_cfg_getResponse (60)
/* complex XML schema type 'ns1:audio-cfg-getResponse': */
struct ns1__audio_cfg_getResponse {
        /** Optional element 'cfg-data' of XML schema type 'xsd:string' */
        char **cfg_data;
};
#endif

/* hello.h:286 */
#ifndef SOAP_TYPE_ns1__audio_cfg_get
#define SOAP_TYPE_ns1__audio_cfg_get (61)
/* complex XML schema type 'ns1:audio-cfg-get': */
struct ns1__audio_cfg_get {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* hello.h:289 */
#ifndef SOAP_TYPE_ns1__osd_text_setResponse
#define SOAP_TYPE_ns1__osd_text_setResponse (63)
/* complex XML schema type 'ns1:osd-text-setResponse': */
struct ns1__osd_text_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:289 */
#ifndef SOAP_TYPE_ns1__osd_text_set
#define SOAP_TYPE_ns1__osd_text_set (64)
/* complex XML schema type 'ns1:osd-text-set': */
struct ns1__osd_text_set {
        /** Optional element 'text-data' of XML schema type 'xsd:string' */
        char *text_data;
        /** Required element 'len' of XML schema type 'xsd:int' */
        int len;
};
#endif

/* hello.h:291 */
#ifndef SOAP_TYPE_ns1__hdmi_wh_setResponse
#define SOAP_TYPE_ns1__hdmi_wh_setResponse (66)
/* complex XML schema type 'ns1:hdmi-wh-setResponse': */
struct ns1__hdmi_wh_setResponse {
        /** Optional element 'ret' of XML schema type 'xsd:int' */
        int *ret;
};
#endif

/* hello.h:291 */
#ifndef SOAP_TYPE_ns1__hdmi_wh_set
#define SOAP_TYPE_ns1__hdmi_wh_set (67)
/* complex XML schema type 'ns1:hdmi-wh-set': */
struct ns1__hdmi_wh_set {
        /** Required element 'w' of XML schema type 'xsd:int' */
        int w;
        /** Required element 'h' of XML schema type 'xsd:int' */
        int h;
        /** Required element 'fps' of XML schema type 'xsd:int' */
        int fps;
};
#endif

/* hello.h:301 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (68)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* hello.h:301 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (69)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* hello.h:301 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (71)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* hello.h:301 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (73)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* hello.h:301 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (74)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (74)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (73)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (71)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (69)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (68)
#endif

/* struct ns1__hdmi_wh_set has binding name 'ns1__hdmi_wh_set' for type 'ns1:hdmi-wh-set' */
#ifndef SOAP_TYPE_ns1__hdmi_wh_set
#define SOAP_TYPE_ns1__hdmi_wh_set (67)
#endif

/* struct ns1__hdmi_wh_setResponse has binding name 'ns1__hdmi_wh_setResponse' for type 'ns1:hdmi-wh-setResponse' */
#ifndef SOAP_TYPE_ns1__hdmi_wh_setResponse
#define SOAP_TYPE_ns1__hdmi_wh_setResponse (66)
#endif

/* struct ns1__osd_text_set has binding name 'ns1__osd_text_set' for type 'ns1:osd-text-set' */
#ifndef SOAP_TYPE_ns1__osd_text_set
#define SOAP_TYPE_ns1__osd_text_set (64)
#endif

/* struct ns1__osd_text_setResponse has binding name 'ns1__osd_text_setResponse' for type 'ns1:osd-text-setResponse' */
#ifndef SOAP_TYPE_ns1__osd_text_setResponse
#define SOAP_TYPE_ns1__osd_text_setResponse (63)
#endif

/* struct ns1__audio_cfg_get has binding name 'ns1__audio_cfg_get' for type 'ns1:audio-cfg-get' */
#ifndef SOAP_TYPE_ns1__audio_cfg_get
#define SOAP_TYPE_ns1__audio_cfg_get (61)
#endif

/* struct ns1__audio_cfg_getResponse has binding name 'ns1__audio_cfg_getResponse' for type 'ns1:audio-cfg-getResponse' */
#ifndef SOAP_TYPE_ns1__audio_cfg_getResponse
#define SOAP_TYPE_ns1__audio_cfg_getResponse (60)
#endif

/* struct ns1__audio_cfg_set has binding name 'ns1__audio_cfg_set' for type 'ns1:audio-cfg-set' */
#ifndef SOAP_TYPE_ns1__audio_cfg_set
#define SOAP_TYPE_ns1__audio_cfg_set (58)
#endif

/* struct ns1__audio_cfg_setResponse has binding name 'ns1__audio_cfg_setResponse' for type 'ns1:audio-cfg-setResponse' */
#ifndef SOAP_TYPE_ns1__audio_cfg_setResponse
#define SOAP_TYPE_ns1__audio_cfg_setResponse (57)
#endif

/* struct ns1__video_cfg_get has binding name 'ns1__video_cfg_get' for type 'ns1:video-cfg-get' */
#ifndef SOAP_TYPE_ns1__video_cfg_get
#define SOAP_TYPE_ns1__video_cfg_get (55)
#endif

/* struct ns1__video_cfg_getResponse has binding name 'ns1__video_cfg_getResponse' for type 'ns1:video-cfg-getResponse' */
#ifndef SOAP_TYPE_ns1__video_cfg_getResponse
#define SOAP_TYPE_ns1__video_cfg_getResponse (54)
#endif

/* struct ns1__video_cfg_set has binding name 'ns1__video_cfg_set' for type 'ns1:video-cfg-set' */
#ifndef SOAP_TYPE_ns1__video_cfg_set
#define SOAP_TYPE_ns1__video_cfg_set (52)
#endif

/* struct ns1__video_cfg_setResponse has binding name 'ns1__video_cfg_setResponse' for type 'ns1:video-cfg-setResponse' */
#ifndef SOAP_TYPE_ns1__video_cfg_setResponse
#define SOAP_TYPE_ns1__video_cfg_setResponse (51)
#endif

/* struct ns1__status_notify has binding name 'ns1__status_notify' for type 'ns1:status-notify' */
#ifndef SOAP_TYPE_ns1__status_notify
#define SOAP_TYPE_ns1__status_notify (49)
#endif

/* struct ns1__log_info has binding name 'ns1__log_info' for type 'ns1:log-info' */
#ifndef SOAP_TYPE_ns1__log_info
#define SOAP_TYPE_ns1__log_info (47)
#endif

/* struct ns1__video_interval_set has binding name 'ns1__video_interval_set' for type 'ns1:video-interval-set' */
#ifndef SOAP_TYPE_ns1__video_interval_set
#define SOAP_TYPE_ns1__video_interval_set (44)
#endif

/* struct ns1__video_interval_setResponse has binding name 'ns1__video_interval_setResponse' for type 'ns1:video-interval-setResponse' */
#ifndef SOAP_TYPE_ns1__video_interval_setResponse
#define SOAP_TYPE_ns1__video_interval_setResponse (43)
#endif

/* struct ns1__video_interval_get has binding name 'ns1__video_interval_get' for type 'ns1:video-interval-get' */
#ifndef SOAP_TYPE_ns1__video_interval_get
#define SOAP_TYPE_ns1__video_interval_get (41)
#endif

/* struct ns1__video_interval_getResponse has binding name 'ns1__video_interval_getResponse' for type 'ns1:video-interval-getResponse' */
#ifndef SOAP_TYPE_ns1__video_interval_getResponse
#define SOAP_TYPE_ns1__video_interval_getResponse (40)
#endif

/* struct ns1__video_bitrate_set has binding name 'ns1__video_bitrate_set' for type 'ns1:video-bitrate-set' */
#ifndef SOAP_TYPE_ns1__video_bitrate_set
#define SOAP_TYPE_ns1__video_bitrate_set (38)
#endif

/* struct ns1__video_bitrate_setResponse has binding name 'ns1__video_bitrate_setResponse' for type 'ns1:video-bitrate-setResponse' */
#ifndef SOAP_TYPE_ns1__video_bitrate_setResponse
#define SOAP_TYPE_ns1__video_bitrate_setResponse (37)
#endif

/* struct ns1__video_bitrate_get has binding name 'ns1__video_bitrate_get' for type 'ns1:video-bitrate-get' */
#ifndef SOAP_TYPE_ns1__video_bitrate_get
#define SOAP_TYPE_ns1__video_bitrate_get (35)
#endif

/* struct ns1__video_bitrate_getResponse has binding name 'ns1__video_bitrate_getResponse' for type 'ns1:video-bitrate-getResponse' */
#ifndef SOAP_TYPE_ns1__video_bitrate_getResponse
#define SOAP_TYPE_ns1__video_bitrate_getResponse (34)
#endif

/* struct ns1__video_wh_set has binding name 'ns1__video_wh_set' for type 'ns1:video-wh-set' */
#ifndef SOAP_TYPE_ns1__video_wh_set
#define SOAP_TYPE_ns1__video_wh_set (32)
#endif

/* struct ns1__video_wh_setResponse has binding name 'ns1__video_wh_setResponse' for type 'ns1:video-wh-setResponse' */
#ifndef SOAP_TYPE_ns1__video_wh_setResponse
#define SOAP_TYPE_ns1__video_wh_setResponse (31)
#endif

/* struct ns1__video_wh_get has binding name 'ns1__video_wh_get' for type 'ns1:video-wh-get' */
#ifndef SOAP_TYPE_ns1__video_wh_get
#define SOAP_TYPE_ns1__video_wh_get (29)
#endif

/* struct ns1__video_wh_getResponse has binding name 'ns1__video_wh_getResponse' for type 'ns1:video-wh-getResponse' */
#ifndef SOAP_TYPE_ns1__video_wh_getResponse
#define SOAP_TYPE_ns1__video_wh_getResponse (28)
#endif

/* struct ns1__video_fps_set has binding name 'ns1__video_fps_set' for type 'ns1:video-fps-set' */
#ifndef SOAP_TYPE_ns1__video_fps_set
#define SOAP_TYPE_ns1__video_fps_set (26)
#endif

/* struct ns1__video_fps_setResponse has binding name 'ns1__video_fps_setResponse' for type 'ns1:video-fps-setResponse' */
#ifndef SOAP_TYPE_ns1__video_fps_setResponse
#define SOAP_TYPE_ns1__video_fps_setResponse (25)
#endif

/* struct ns1__video_fps_get has binding name 'ns1__video_fps_get' for type 'ns1:video-fps-get' */
#ifndef SOAP_TYPE_ns1__video_fps_get
#define SOAP_TYPE_ns1__video_fps_get (23)
#endif

/* struct ns1__video_fps_getResponse has binding name 'ns1__video_fps_getResponse' for type 'ns1:video-fps-getResponse' */
#ifndef SOAP_TYPE_ns1__video_fps_getResponse
#define SOAP_TYPE_ns1__video_fps_getResponse (22)
#endif

/* struct ns1__audio_button_status_get has binding name 'ns1__audio_button_status_get' for type 'ns1:audio-button-status-get' */
#ifndef SOAP_TYPE_ns1__audio_button_status_get
#define SOAP_TYPE_ns1__audio_button_status_get (20)
#endif

/* struct ns1__audio_button_status_getResponse has binding name 'ns1__audio_button_status_getResponse' for type 'ns1:audio-button-status-getResponse' */
#ifndef SOAP_TYPE_ns1__audio_button_status_getResponse
#define SOAP_TYPE_ns1__audio_button_status_getResponse (19)
#endif

/* struct ns1__audio_sample_get has binding name 'ns1__audio_sample_get' for type 'ns1:audio-sample-get' */
#ifndef SOAP_TYPE_ns1__audio_sample_get
#define SOAP_TYPE_ns1__audio_sample_get (17)
#endif

/* struct ns1__audio_sample_getResponse has binding name 'ns1__audio_sample_getResponse' for type 'ns1:audio-sample-getResponse' */
#ifndef SOAP_TYPE_ns1__audio_sample_getResponse
#define SOAP_TYPE_ns1__audio_sample_getResponse (16)
#endif

/* struct ns1__audio_sample_set has binding name 'ns1__audio_sample_set' for type 'ns1:audio-sample-set' */
#ifndef SOAP_TYPE_ns1__audio_sample_set
#define SOAP_TYPE_ns1__audio_sample_set (14)
#endif

/* struct ns1__audio_sample_setResponse has binding name 'ns1__audio_sample_setResponse' for type 'ns1:audio-sample-setResponse' */
#ifndef SOAP_TYPE_ns1__audio_sample_setResponse
#define SOAP_TYPE_ns1__audio_sample_setResponse (13)
#endif

/* struct ns1__sayHello has binding name 'ns1__sayHello' for type 'ns1:sayHello' */
#ifndef SOAP_TYPE_ns1__sayHello
#define SOAP_TYPE_ns1__sayHello (10)
#endif

/* struct ns1__sayHelloResponse has binding name 'ns1__sayHelloResponse' for type 'ns1:sayHelloResponse' */
#ifndef SOAP_TYPE_ns1__sayHelloResponse
#define SOAP_TYPE_ns1__sayHelloResponse (9)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (76)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (75)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (70)
#endif

/* int * has binding name 'PointerToint' for type 'xsd:int' */
#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (11)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (7)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    
    /** Web service synchronous operation 'soap_call_ns1__sayHello' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sayHello(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *firstName, char **greeting);
    /** Web service asynchronous operation 'soap_send_ns1__sayHello' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__sayHello(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *firstName);
    /** Web service asynchronous operation 'soap_recv_ns1__sayHello' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__sayHello(struct soap *soap, char **greeting);
    
    /** Web service synchronous operation 'soap_call_ns1__audio_sample_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_sample_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int sample, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__audio_sample_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_sample_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int sample);
    /** Web service asynchronous operation 'soap_recv_ns1__audio_sample_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_sample_set(struct soap *soap, int *ret);
    
    /** Web service synchronous operation 'soap_call_ns1__audio_sample_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_sample_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *sample);
    /** Web service asynchronous operation 'soap_send_ns1__audio_sample_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_sample_get(struct soap *soap, const char *soap_endpoint, const char *soap_action);
    /** Web service asynchronous operation 'soap_recv_ns1__audio_sample_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_sample_get(struct soap *soap, int *sample);
    
    /** Web service synchronous operation 'soap_call_ns1__audio_button_status_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_button_status_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *status);
    /** Web service asynchronous operation 'soap_send_ns1__audio_button_status_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_button_status_get(struct soap *soap, const char *soap_endpoint, const char *soap_action);
    /** Web service asynchronous operation 'soap_recv_ns1__audio_button_status_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_button_status_get(struct soap *soap, int *status);
    
    /** Web service synchronous operation 'soap_call_ns1__video_fps_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_fps_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *fps);
    /** Web service asynchronous operation 'soap_send_ns1__video_fps_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_fps_get(struct soap *soap, const char *soap_endpoint, const char *soap_action);
    /** Web service asynchronous operation 'soap_recv_ns1__video_fps_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_fps_get(struct soap *soap, int *fps);
    
    /** Web service synchronous operation 'soap_call_ns1__video_fps_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_fps_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int fps, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__video_fps_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_fps_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int fps);
    /** Web service asynchronous operation 'soap_recv_ns1__video_fps_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_fps_set(struct soap *soap, int *ret);
    
    /** Web service synchronous operation 'soap_call_ns1__video_wh_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_wh_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *w, int *h);
    /** Web service asynchronous operation 'soap_send_ns1__video_wh_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_wh_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *w);
    /** Web service asynchronous operation 'soap_recv_ns1__video_wh_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_wh_get(struct soap *soap, int *h);
    
    /** Web service synchronous operation 'soap_call_ns1__video_wh_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__video_wh_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h);
    /** Web service asynchronous operation 'soap_recv_ns1__video_wh_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_wh_set(struct soap *soap, int *ret);
    
    /** Web service synchronous operation 'soap_call_ns1__video_bitrate_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_bitrate_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *bitrate_max, int *bitrate_min);
    /** Web service asynchronous operation 'soap_send_ns1__video_bitrate_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_bitrate_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *bitrate_max);
    /** Web service asynchronous operation 'soap_recv_ns1__video_bitrate_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_bitrate_get(struct soap *soap, int *bitrate_min);
    
    /** Web service synchronous operation 'soap_call_ns1__video_bitrate_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_bitrate_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int bitrate_max, int bitrate_min, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__video_bitrate_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_bitrate_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int bitrate_max, int bitrate_min);
    /** Web service asynchronous operation 'soap_recv_ns1__video_bitrate_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_bitrate_set(struct soap *soap, int *ret);
    
    /** Web service synchronous operation 'soap_call_ns1__video_interval_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_interval_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *i_interval);
    /** Web service asynchronous operation 'soap_send_ns1__video_interval_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_interval_get(struct soap *soap, const char *soap_endpoint, const char *soap_action);
    /** Web service asynchronous operation 'soap_recv_ns1__video_interval_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_interval_get(struct soap *soap, int *i_interval);
    
    /** Web service synchronous operation 'soap_call_ns1__video_interval_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_interval_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int i_interval, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__video_interval_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_interval_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int i_interval);
    /** Web service asynchronous operation 'soap_recv_ns1__video_interval_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_interval_set(struct soap *soap, int *ret);
    /** Web service one-way asynchronous operation 'soap_send_ns1__log_info' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__log_info(struct soap *soap, const char *soap_endpoint, const char *soap_action, const char *info);
    /** Web service one-way asynchronous operation 'soap_recv_ns1__log_info' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__log_info(struct soap *soap, struct ns1__log_info *_param_1);
    /** Web service one-way asynchronous operation 'soap_send_ns1__status_notify' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__status_notify(struct soap *soap, const char *soap_endpoint, const char *soap_action, const char *info);
    /** Web service one-way asynchronous operation 'soap_recv_ns1__status_notify' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__status_notify(struct soap *soap, struct ns1__status_notify *_param_1);
    
    /** Web service synchronous operation 'soap_call_ns1__video_cfg_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__video_cfg_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len);
    /** Web service asynchronous operation 'soap_recv_ns1__video_cfg_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_cfg_set(struct soap *soap, int *ret);
    
    /** Web service synchronous operation 'soap_call_ns1__video_cfg_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__video_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **cfg_data);
    /** Web service asynchronous operation 'soap_send_ns1__video_cfg_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__video_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action);
    /** Web service asynchronous operation 'soap_recv_ns1__video_cfg_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__video_cfg_get(struct soap *soap, char **cfg_data);
    
    /** Web service synchronous operation 'soap_call_ns1__audio_cfg_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__audio_cfg_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_cfg_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *cfg_data, int len);
    /** Web service asynchronous operation 'soap_recv_ns1__audio_cfg_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_cfg_set(struct soap *soap, int *ret);
    
    /** Web service synchronous operation 'soap_call_ns1__audio_cfg_get' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__audio_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **cfg_data);
    /** Web service asynchronous operation 'soap_send_ns1__audio_cfg_get' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__audio_cfg_get(struct soap *soap, const char *soap_endpoint, const char *soap_action);
    /** Web service asynchronous operation 'soap_recv_ns1__audio_cfg_get' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__audio_cfg_get(struct soap *soap, char **cfg_data);
    
    /** Web service synchronous operation 'soap_call_ns1__osd_text_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__osd_text_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *text_data, int len, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__osd_text_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__osd_text_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *text_data, int len);
    /** Web service asynchronous operation 'soap_recv_ns1__osd_text_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__osd_text_set(struct soap *soap, int *ret);
    
    /** Web service synchronous operation 'soap_call_ns1__hdmi_wh_set' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__hdmi_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h, int fps, int *ret);
    /** Web service asynchronous operation 'soap_send_ns1__hdmi_wh_set' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_ns1__hdmi_wh_set(struct soap *soap, const char *soap_endpoint, const char *soap_action, int w, int h, int fps);
    /** Web service asynchronous operation 'soap_recv_ns1__hdmi_wh_set' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_ns1__hdmi_wh_set(struct soap *soap, int *ret);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation 'ns1__sayHello' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__sayHello(struct soap*, char *firstName, char **greeting);
    /** Web service operation 'ns1__audio_sample_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__audio_sample_set(struct soap*, int sample, int *ret);
    /** Web service operation 'ns1__audio_sample_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__audio_sample_get(struct soap*, int *sample);
    /** Web service operation 'ns1__audio_button_status_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__audio_button_status_get(struct soap*, int *status);
    /** Web service operation 'ns1__video_fps_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_fps_get(struct soap*, int *fps);
    /** Web service operation 'ns1__video_fps_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_fps_set(struct soap*, int fps, int *ret);
    /** Web service operation 'ns1__video_wh_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_wh_get(struct soap*, int *w, int *h);
    /** Web service operation 'ns1__video_wh_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_wh_set(struct soap*, int w, int h, int *ret);
    /** Web service operation 'ns1__video_bitrate_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_bitrate_get(struct soap*, int *bitrate_max, int *bitrate_min);
    /** Web service operation 'ns1__video_bitrate_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_bitrate_set(struct soap*, int bitrate_max, int bitrate_min, int *ret);
    /** Web service operation 'ns1__video_interval_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_interval_get(struct soap*, int *i_interval);
    /** Web service operation 'ns1__video_interval_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_interval_set(struct soap*, int i_interval, int *ret);
    /** Web service one-way operation 'ns1__log_info' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__log_info(struct soap*, const char *info);
    /** Web service one-way operation 'ns1__status_notify' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__status_notify(struct soap*, const char *info);
    /** Web service operation 'ns1__video_cfg_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_cfg_set(struct soap*, char *cfg_data, int len, int *ret);
    /** Web service operation 'ns1__video_cfg_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__video_cfg_get(struct soap*, char **cfg_data);
    /** Web service operation 'ns1__audio_cfg_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__audio_cfg_set(struct soap*, char *cfg_data, int len, int *ret);
    /** Web service operation 'ns1__audio_cfg_get' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__audio_cfg_get(struct soap*, char **cfg_data);
    /** Web service operation 'ns1__osd_text_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__osd_text_set(struct soap*, char *text_data, int len, int *ret);
    /** Web service operation 'ns1__hdmi_wh_set' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 ns1__hdmi_wh_set(struct soap*, int w, int h, int fps, int *ret);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__sayHello(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_sample_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_sample_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_button_status_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_fps_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_fps_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_wh_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_wh_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_bitrate_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_bitrate_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_interval_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_interval_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__log_info(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__status_notify(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_cfg_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__video_cfg_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_cfg_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__audio_cfg_get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__osd_text_set(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__hdmi_wh_set(struct soap*);

#endif

/* End of soapStub.h */
